### ISSUE TITLE
passing Defines to PpLexer

### ISSUE THREAD

**Issue by lebhero** [paulross/cpip#17]
For some reason I am not able to pass Defines to the PpLexer using the preDefines.
Like in the Demo, how do i pass AUSTRALIAN & LANG_SUPPORT for example ?

`myLex = PpLexer.PpLexer(cpp_file, handlerObj)`

**Comment by paulross** [comment]
Ah, yes the API is a bit obscure!

The `PpLexer.PpLexer` reference is here: https://cpip.readthedocs.io/en/latest/ref/core/PpLexer.html#

What you need to do is to use the `preIncFiles` argument with is a list of file-like objects that will be included and pre-processed before any other pre-processing. These file(s) can include `#define` statements. An example is in the unit tests here: https://github.com/paulross/cpip/blob/master/tests/unit/test_core/test_PpLexer.py#L107

Please close this issue if you feel that this is satisfactory answer.

**Comment by lebhero** [comment]
Works... thank you Paul.. any plans on updating the lib to support python 3.10?

**Comment by paulross** [comment]
Yes, let me see if I can get some time over Xmas, it shouldn't be too hard.
